from __future__ import annotations

import json
import subprocess
import time
from pathlib import Path
from uuid import uuid4

import httpx

from app.core.config import get_settings
from app.core.time_utils import iso_now
from app.evals.harness import run_minimal_eval
from app.memory.service import get_memory_service


class ProductService:
    def __init__(self) -> None:
        self.settings = get_settings()
        self.memory = get_memory_service()
        self.root = Path("/home/saganski/workspace/experiments/cortexos")

    def dashboard(self) -> dict:
        stats = self.memory.dashboard_stats()
        timeline = self.memory.timeline(limit=200)
        operations = self.operations_status()
        return {
            "stats": stats,
            "timeline": timeline["series"],
            "operations": operations,
        }

    def operations_status(self) -> dict:
        db_path = self.settings.db_path
        qdrant_dir = self.root / "ops" / "qdrant" / "data"
        searx_settings = self.root / "ops" / "searxng" / "settings.yml"
        return {
            "health": self.memory.health() | {"api": "ok", "status": "ok"},
            "runtime": self.memory.runtime_state(),
            "ports": {
                "api": self.settings.port,
                "qdrant_http": 6333,
                "qdrant_grpc": 6334,
                "searxng": 8787,
                "ollama": 11434,
            },
            "storage": {
                "sqlite_bytes": db_path.stat().st_size if db_path.exists() else 0,
                "qdrant_bytes": self._dir_size(qdrant_dir),
                "searx_settings_bytes": (
                    searx_settings.stat().st_size if searx_settings.exists() else 0
                ),
            },
            "service": self._service_summary(),
            "containers": self._containers_summary(),
            "api_logs": self._journal_summary(),
            "available_models": self._ollama_models(),
            "recent_queries": self.memory.repo.list_query_runs(limit=10),
            "recent_evals": self.memory.repo.list_eval_runs(limit=10),
        }

    def settings_summary(self) -> dict:
        return {
            "runtime": {
                "env": self.settings.env,
                "host": self.settings.host,
                "port": self.settings.port,
                "llm_synthesis_enabled": self.settings.enable_llm_synthesis,
                "default_model": self.settings.default_model,
                "quality_model": self.settings.quality_model,
                "code_model": self.settings.code_model,
                "embedding_backend": self.settings.embedding_backend,
                "rerank_backend": self.settings.rerank_backend,
            },
            "modes": [
                {
                    "id": "fast",
                    "label": "Fast",
                    "description": "Lower latency. Deterministic synthesis. Smaller candidate set.",
                },
                {
                    "id": "balanced",
                    "label": "Balanced",
                    "description": (
                        "Default. Full hybrid retrieval and rerank. "
                        "LLM allowed if enabled."
                    ),
                },
                {
                    "id": "deep",
                    "label": "Deep",
                    "description": (
                        "Largest explain surface and candidate set "
                        "for demos and debugging."
                    ),
                },
            ],
        }

    def run_smoke_test(self) -> dict:
        started = time.perf_counter()
        proc = subprocess.run(
            ["bash", "scripts/smoke_test.sh"],
            cwd=self.root,
            capture_output=True,
            text=True,
            check=False,
        )
        return {
            "success": proc.returncode == 0,
            "returncode": proc.returncode,
            "stdout": proc.stdout,
            "stderr": proc.stderr,
            "total_ms": round((time.perf_counter() - started) * 1000, 2),
            "created_at": iso_now(),
        }

    def run_eval(self, mode: str) -> dict:
        started = time.perf_counter()
        result = run_minimal_eval(mode=mode)
        total_ms = round((time.perf_counter() - started) * 1000, 2)
        run_id = f"eval_{uuid4().hex}"
        self.memory.repo.record_eval_run(
            run_id=run_id,
            suite_name="minimal",
            mode=mode,
            success=bool(result["passed"]),
            total_ms=total_ms,
            results=result,
            notes="Generated by operations/evals product endpoint.",
            created_at=iso_now(),
        )
        return {"run_id": run_id, "total_ms": total_ms, **result}

    def list_eval_runs(self) -> list[dict]:
        return self.memory.repo.list_eval_runs(limit=30)

    def get_eval_run(self, run_id: str) -> dict | None:
        return self.memory.repo.get_eval_run(run_id)

    @staticmethod
    def _dir_size(path: Path) -> int:
        if not path.exists():
            return 0
        return sum(item.stat().st_size for item in path.rglob("*") if item.is_file())

    def _service_summary(self) -> dict:
        try:
            proc = subprocess.run(
                ["systemctl", "show", "cortexos-api", "--property=ActiveState,SubState,MainPID"],
                capture_output=True,
                text=True,
                check=False,
            )
            lines = [line for line in proc.stdout.splitlines() if "=" in line]
            return {
                "raw": proc.stdout.strip(),
                "fields": {key: value for key, value in (line.split("=", 1) for line in lines)},
            }
        except Exception as exc:
            return {"error": str(exc)}

    def _containers_summary(self) -> dict:
        try:
            proc = subprocess.run(
                ["docker", "compose", "ps", "--format", "json"],
                cwd=self.root,
                capture_output=True,
                text=True,
                check=False,
            )
            raw = proc.stdout.strip()
            if not raw:
                return {"items": []}
            items = [json.loads(line) for line in raw.splitlines()]
            return {"items": items}
        except Exception as exc:
            return {"error": str(exc)}

    def _journal_summary(self) -> list[str]:
        try:
            proc = subprocess.run(
                ["journalctl", "-u", "cortexos-api", "-n", "20", "--no-pager", "-q"],
                capture_output=True,
                text=True,
                check=False,
            )
            return [line for line in proc.stdout.splitlines() if line.strip()][-20:]
        except Exception as exc:
            return [f"journal unavailable: {exc}"]

    def _ollama_models(self) -> list[dict]:
        try:
            response = httpx.get(f"{self.settings.ollama_url}/api/tags", timeout=10)
            response.raise_for_status()
            return response.json().get("models", [])
        except Exception:
            return []
